@API_HostAddress = http://localhost:5253
#@API_HostAddress = http://1.10.143.138:8429/BarCodeBackEnd


#http://localhost/APITRIWALL http://192.168.10.2/AddOnProgram
#http://localhost:8429/BarCodeBackEnd/HeloWorld

###

GET {{API_HostAddress}}/HeloWord
###

POST {{API_HostAddress}}/getQuery
Content-Type: application/json

# {
#   "StoreName": "_USP_CALLTRANS_EWTRANSACTION",
#   "DBType": "SERIES",
#   "Par1": "60",
#   "Par2": "",
#   "Par3": "",
#   "Par4": "",
#   "Par5": ""
# }
{"storeName":"_USP_CALLTRANS_EWTRANSACTION","dbType":"OnGetBatchOrSerialInIssueForProduction","par1":"B","par2":"TEST-B-01","par3":"","par4":"","par5":""}

###

POST {{API_HostAddress}}/goodReceiptPo
Content-Type: application/json

{
    "VendorCode": "V-A001-00",
    "ContactPersonCode": 0,
    "VendorNo": "",
    "Series": 0,
    "DocDate": "2024-05-11",
    "TaxDate": "2024-05-11",
    "Remarks": "",
    "isDraft": true,
    "Lines": [
        {
            "ItemCode": "RIIP4401390INP",
            "Qty": 10,
            "Price": 10,
            "VatCode": "P00",
            "WarehouseCode": "AS01",
            "ManageItem": "N",
            "LineStatus": 0
        }
    ]
}

###

POST {{API_HostAddress}}/deliveryOrders
Content-Type: application/json

{
    "CardCode": "C-T008-00",
    "ContactPersonCode": 0,
    "NumAtCard": "PO-2401-00001",
    "Series": 0,
    "DocDate": "2024-05-11",
    "TaxDate": "2024-05-11",
    "Remarks": "",
    "Lines": [
        {
            "ItemCode": "T008-1SB0002-00",
            "Qty": 200,
            "Price": 300,
            "VatCode": "S00",
            "WarehouseCode": "FG01",
            "ManageItem": "N",
            "LineStatus": 0
        }
    ]
}

###

POST {{API_HostAddress}}/purchaseOrders
Content-Type: application/json

{
    "CardCode": "C-T008-00",
    "ContactPersonCode": 0,
    "NumAtCard": "PO-2401-00001",
    "Series": 0,
    "DocDate": "2024-05-11",
    "TaxDate": "2024-05-11",
    "Remarks": "",
    "Lines": [
        {
            "ItemCode": "T008-1SB0002-00",
            "Qty": 200,
            "Price": 300,
            "VatCode": "S00",
            "WarehouseCode": "FG01",
            "ManageItem": "N",
            "LineStatus": 0
        }
    ]
}

###

POST {{API_HostAddress}}/issueForProduction
Content-Type: application/json

{
  "series": "335",
  "remarks": "",
  "docDate": "2024-06-14T00:00:00",
  "lines": [
    {
      "docNum": "714",
      "lineNum": 0,
      "baseLineNum": 1,
      "itemCode": "RLCA1501390IPP",
      "itemName": "MEDIUM_CA150_S.1390",
      "qty": 1.6666666666666665,
      "qtyRequire": 0,
      "price": 0,
      "whsCode": "RM01",
      "uomName": "Manual",
      "ManageItem": "N"
    },
    {
      "docNum": "714",
      "lineNum": 0,
      "baseLineNum": 2,
      "itemCode": "RLCA1501390IPP",
      "itemName": "MEDIUM_CA150_S.1390",
      "qty": 1.6666666666666665,
      "qtyRequire": 0,
      "price": 0,
      "whsCode": "RM01",
      "uomName": "Manual",
      "ManageItem": "N"
    },
    {
      "docNum": "714",
      "lineNum": 0,
      "baseLineNum": 3,
      "itemCode": "RLCA1501390IPP",
      "itemName": "MEDIUM_CA150_S.1390",
      "qty": 1.6666666666666665,
      "qtyRequire": 0,
      "price": 0,
      "whsCode": "RM01",
      "uomName": "Manual",
      "ManageItem": "N"
    }
  ]
}