@API_HostAddress = http://localhost:5253


GET {{API_HostAddress}}/todos/
Accept: application/json

###

POST {{API_HostAddress}}/getQuery
Content-Type: application/json

{
    "StoreName": "_USP_CALLTRANS_EWTRANSACTION",
    "DBType": "GetItem",
    "Par1": "",
    "Par2": "",
    "Par3": "",
    "Par4": "",
    "Par5": ""
}

###

POST {{API_HostAddress}}/goodReceiptPo
Content-Type: application/json

{
    "VendorCode": "V-A001-00",
    "ContactPersonCode": 0,
    "VendorNo": "",
    "Series": 0,
    "DocDate": "2024-05-11",
    "TaxDate": "2024-05-11",
    "Remarks": "",
    "isDraft": true,
    "Lines": [
        {
            "ItemCode": "RIIP4401390INP",
            "Qty": 10,
            "Price": 10,
            "VatCode": "P00",
            "WarehouseCode": "AS01",
            "ManageItem": "N",
            "LineStatus": 0
        }
    ]
}

###

POST {{API_HostAddress}}/deliveryOrders
Content-Type: application/json

{
    "CardCode": "C-T008-00",
    "ContactPersonCode": 0,
    "NumAtCard": "PO-2401-00001",
    "Series": 0,
    "DocDate": "2024-05-11",
    "TaxDate": "2024-05-11",
    "Remarks": "",
    "Lines": [
        {
            "ItemCode": "T008-1SB0002-00",
            "Qty": 200,
            "Price": 300,
            "VatCode": "S00",
            "WarehouseCode": "FG01",
            "ManageItem": "N",
            "LineStatus": 0
        }
    ]
}

###

POST {{API_HostAddress}}/purchaseOrders
Content-Type: application/json

{
    "CardCode": "C-T008-00",
    "ContactPersonCode": 0,
    "NumAtCard": "PO-2401-00001",
    "Series": 0,
    "DocDate": "2024-05-11",
    "TaxDate": "2024-05-11",
    "Remarks": "",
    "Lines": [
        {
            "ItemCode": "T008-1SB0002-00",
            "Qty": 200,
            "Price": 300,
            "VatCode": "S00",
            "WarehouseCode": "FG01",
            "ManageItem": "N",
            "LineStatus": 0
        }
    ]
}