@API_HostAddress = http://localhost:5253
# @API_HostAddress = http://192.168.10.107:8429/ApiTriWall/


#http://localhost/APITRIWALL http://192.168.10.2/AddOnProgram
#http://localhost:8429/BarCodeBackEnd/HeloWorld

###

GET {{API_HostAddress}}/HeloWord
###

POST {{API_HostAddress}}/getQuery
Content-Type: application/json

# {
#   "StoreName": "_USP_CALLTRANS_EWTRANSACTION",
#   "DBType": "SERIES",
#   "Par1": "60",
#   "Par2": "",
#   "Par3": "",
#   "Par4": "",
#   "Par5": ""
# }
{
  "storeName":"_USP_CALLTRANS_EWTRANSACTION",
  "dbType":"GetInventoryCountingLine",
  "par1":"48",
  "par2":"",
  "par3":"",
  "par4":"",
  "par5":""
}

###

POST {{API_HostAddress}}/goodReceiptPo
Content-Type: application/json

{
    "VendorCode": "V-A001-00",
    "ContactPersonCode": 0,
    "VendorNo": "",
    "Series": 0,
    "DocDate": "2024-05-11",
    "TaxDate": "2024-05-11",
    "Remarks": "",
    "isDraft": true,
    "Lines": [
        {
            "ItemCode": "RIIP4401390INP",
            "Qty": 10,
            "Price": 10,
            "VatCode": "P00",
            "WarehouseCode": "AS01",
            "ManageItem": "N",
            "LineStatus": 0
        }
    ]
}

###

POST {{API_HostAddress}}/deliveryOrders
Content-Type: application/json

{
    "CardCode": "C-T008-00",
    "ContactPersonCode": 0,
    "NumAtCard": "PO-2401-00001",
    "Series": 0,
    "DocDate": "2024-05-11",
    "TaxDate": "2024-05-11",
    "Remarks": "",
    "Lines": [
        {
            "ItemCode": "T008-1SB0002-00",
            "Qty": 200,
            "Price": 300,
            "VatCode": "S00",
            "WarehouseCode": "FG01",
            "ManageItem": "N",
            "LineStatus": 0
        }
    ]
}

###

POST {{API_HostAddress}}/purchaseOrders
Content-Type: application/json

{
    "CardCode": "C-T008-00",
    "ContactPersonCode": 0,
    "NumAtCard": "PO-2401-00001",
    "Series": 0,
    "DocDate": "2024-05-11",
    "TaxDate": "2024-05-11",
    "Remarks": "",
    "Lines": [
        {
            "ItemCode": "T008-1SB0002-00",
            "Qty": 200,
            "Price": 300,
            "VatCode": "S00",
            "WarehouseCode": "FG01",
            "ManageItem": "N",
            "LineStatus": 0
        }
    ]
}

###

POST {{API_HostAddress}}/issueForProduction
Content-Type: application/json

{
  "Series": "336",
  "Remarks": "",
  "DocDate": "2024-07-02T00:00:00",
  "Lines": [
    {
      "DocNum": "729",
      "LineNum": 0,
      "BaseLineNum": 0,
      "ItemCode": "TEST-B-01",
      "ItemName": "Batch",
      "Qty": 2,
      "QtyRequire": 0,
      "Price": 0,
      "WhsCode": "RS02",
      "UomName": "Manual",
      "ManageItem": "B",
      "Batches": [
        {
          "BatchCode": "test21",
          "Qty": 2,
          "ExpDate": "2024-06-25T00:00:00",
          "ManfectureDate": "2024-07-02T00:00:00+07:00",
          "AdmissionDate": "2024-07-02T00:00:00+07:00",
          "LotNo": "",
          "QtyAvailable": 0,
          "OnSelectedBatchOrSerial": []
        }
      ],
      "Serials": null
    },
    {
      "DocNum": "730",
      "LineNum": 0,
      "BaseLineNum": 0,
      "ItemCode": "TEST-B-01",
      "ItemName": "Batch",
      "Qty": 2,
      "QtyRequire": 0,
      "Price": 0,
      "WhsCode": "RS02",
      "UomName": "Manual",
      "ManageItem": "B",
      "Batches": [
        {
          "BatchCode": "test21",
          "Qty": 2,
          "ExpDate": "2024-06-25T00:00:00",
          "ManfectureDate": "2024-07-02T00:00:00+07:00",
          "AdmissionDate": "2024-07-02T00:00:00+07:00",
          "LotNo": "",
          "QtyAvailable": 0,
          "OnSelectedBatchOrSerial": []
        }
      ],
      "Serials": null
    },
    {
      "DocNum": "729",
      "LineNum": 0,
      "BaseLineNum": 1,
      "ItemCode": "TEST-S-01",
      "ItemName": "Serial",
      "Qty": 1,
      "QtyRequire": 0,
      "Price": 0,
      "WhsCode": "RS02",
      "UomName": "Manual",
      "ManageItem": "S",
      "Batches": null,
      "Serials": [
        {
          "SerialCode": "t2123t1",
          "Qty": 1,
          "MfrNo": "",
          "MfrDate": "1899-12-30T00:00:00",
          "ExpDate": "1899-12-30T00:00:00",
          "OnSelectedBatchOrSerial": [
            {
              "ItemCode": "TEST-S-01",
              "Qty": "0",
              "SerialBatch": "t2123t1",
              "MfrSerialNo": "",
              "ExpDate": "12/30/1899 00:00:00",
              "MrfDate": "12/30/1899 00:00:00",
              "Type": "Serial",
              "LineNum": null
            }
          ]
        }
      ]
    },
    {
      "DocNum": "730",
      "LineNum": 0,
      "BaseLineNum": 1,
      "ItemCode": "TEST-S-01",
      "ItemName": "Serial",
      "Qty": 1,
      "QtyRequire": 0,
      "Price": 0,
      "WhsCode": "RS02",
      "UomName": "Manual",
      "ManageItem": "S",
      "Batches": null,
      "Serials": [
        {
          "SerialCode": "t2123t2",
          "Qty": 1,
          "MfrNo": "",
          "MfrDate": "1899-12-30T00:00:00",
          "ExpDate": "1899-12-30T00:00:00",
          "OnSelectedBatchOrSerial": [
            {
              "ItemCode": "TEST-S-01",
              "Qty": "0",
              "SerialBatch": "t2123t2",
              "MfrSerialNo": "",
              "ExpDate": "12/30/1899 00:00:00",
              "MrfDate": "12/30/1899 00:00:00",
              "Type": "Serial",
              "LineNum": null
            }
          ]
        }
      ]
    }
  ]
}


###

POST {{API_HostAddress}}/return
Content-Type: application/json

{
  "CustomerCode":"C003",
  "ContactPersonCode":"0",
  "NumAtCard":"",
  "Series":"192",
  "DocDate":"2024-07-19T16:23:30.303+07:00",
  "TaxDate":"2024-07-19T00:00:00",
  "Remarks":"",
  "IsDraft":false,
  "Lines":[
    {
      "ItemCode":"TEST-B-01",
      "ItemName":"Batch",
      "Qty":1,
      "LineNum":1,
      "Price":1,
      "VatCode":"S00",
      "WarehouseCode":"RS02",
      "ManageItem":"B",
      "BaseEntry":0,
      "BaseLine":0,
      "Batches":[
        {
          "BatchCode":"W-01",
          "Qty":1,
          "QtyAvailable":10,
          "ExpDate":"2024-07-09T00:00:00",
          "ManfectureDate":"2024-07-09T00:00:00",
          "AdmissionDate":"2024-07-19T00:00:00+07:00",
          "LotNo":"",
          "OnSelectedBatchOrSerial":[
            {
              "ItemCode":"TEST-B-01",
              "Qty":"10",
              "SerialBatch":"W-01",
              "MfrSerialNo":"",
              "ExpDate":"07/09/2024 00:00:00",
              "MrfDate":"07/09/2024 00:00:00",
              "Type":"Batch",
              "LineNum":null
            }
          ]
        }
      ]
      ,"Serials":[]
    }
  ]
}

###

POST {{API_HostAddress}}/arCreditMemo
Content-Type: application/json

{
  "CustomerCode": "A020-00",
  "ContactPersonCode": 0,
  "NumAtCard": "",
  "Series": "170",
  "DocDate": "2024-07-30T11:15:05.899+07:00",
  "TaxDate": "2024-05-23T00:00:00",
  "Remarks": "",
  "IsDraft": false,
  "Lines": [
    {
      "ItemCode": "20",
      "ItemName": "10",
      "Qty": 1,
      "LineNum": 1,
      "Price": 2,
      "VatCode": "S00",
      "WarehouseCode": "RS02",
      "ManageItem": "S",
      "BaseEntry": 99,
      "BaseLine": 0,
      "Batches": [],
      "Serials": [
        {
          "SerialCode": "1232",
          "Qty": 1,
          "MfrNo": "1232",
          "MfrDate": null,
          "ExpDate": null,
          "OnSelectedBatchOrSerial": [
            {
              "ItemCode": "20",
              "Qty": "1",
              "SerialBatch": "123",
              "MfrSerialNo": "123",
              "ExpDate": "",
              "MrfDate": "",
              "Type": "Serial",
              "LineNum": "1"
            }
          ]
        }
      ]
    }
  ]
}

###

POST {{API_HostAddress}}/inventoryCounting
Content-Type: application/json

{
  "DocEntry":55,
  "CreateTime":"09:39",
  "CreateDate":"2024-07-17T00:00:00",
  "OtherRemark":"",
  "Ref2":"",
  "Series":"240700002",
   "InvnetoryCountingType":"",
      "CountingType":"1",
      "CounterID":"4",
  "Lines":[
    {
      "ItemCode":"T009-1SB0008-00",
      "ItemName":"SHEET BOARD",
      "WhsCode":"RS02",
      "Qty":0,
      "QtyCounted":3,
      "Counted":"",
      "LineNum":0,
      "ManageItem":"S",
      "CountId":0,
      "BinEntry":0,
      "Uom":"Manual",
      "Batches":[],
      "Serials":[
        {
          "ItemCode":"",
          "ConditionSerial":0,
          "Qty":1,
          "SerialCode":"123czxc3",
          "SystemSerialNumber":0,
          "MfrNo":"",
          "Location":"",
          "ReceiptDate":"0001-01-01T00:00:00",
          "BinEntry":0,
          "IsSerialNew":"Y",
          "OnSelectedBatchOrSerial":[]
        },
        {
          "ItemCode":"",
          "ConditionSerial":0,
          "Qty":1,
          "SerialCode":"3gasdvb",
          "SystemSerialNumber":0,
          "MfrNo":"",
          "Location":"",
          "BinEntry":0,
          "IsSerialNew":"Y",
          "OnSelectedBatchOrSerial":[]
        }
      ]
    }
  ]
}

###